import 'package:flutter/material.dart';
import 'package:vibration/vibration.dart';
import '../../core/api/api_client.dart';
import '../../core/location/location_service.dart';
import '../../core/offline/offline_queue.dart';
class EmergencyRequestScreen extends StatefulWidget { const EmergencyRequestScreen({super.key}); @override State<EmergencyRequestScreen> createState() => _EmergencyRequestScreenState(); }
class _EmergencyRequestScreenState extends State<EmergencyRequestScreen> { final patient = TextEditingController(), hospital = TextEditingController(), phone = TextEditingController(); String blood = 'B+'; int units = 1; bool busy = false; final api = ApiClient(); late final OfflineQueue queue = OfflineQueue(api);
 Future<void> submit() async { setState(() => busy = true); final p = await LocationService().currentPosition(); final data = {'patient_name': patient.text, 'blood_group': blood, 'component': 'WHOLE_BLOOD', 'units_needed': units, 'hospital_name': hospital.text, 'latitude': p?.latitude, 'longitude': p?.longitude, 'urgency': 'CRITICAL_IMMEDIATE', 'contact_phone': phone.text}; try { await api.post('/requests/', data: data); if (await Vibration.hasVibrator() == true) Vibration.vibrate(duration: 150); if (mounted) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Emergency request created'))); Navigator.pop(context); } } catch (_) { queue.enqueue((client) => client.post('/requests/', data: data)); if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Saved to reconnect queue; will retry when online'))); } finally { if (mounted) setState(() => busy = false); } }
 @override void dispose() { queue.dispose(); patient.dispose(); hospital.dispose(); phone.dispose(); super.dispose(); }
 @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Emergency blood request')), body: ListView(padding: const EdgeInsets.all(20), children: [TextField(controller: patient, decoration: const InputDecoration(labelText: 'Patient name')), DropdownButtonFormField(value: blood, items: const ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'].map((v) => DropdownMenuItem(value: v, child: Text(v))).toList(), onChanged: (v) => setState(() => blood = v!), decoration: const InputDecoration(labelText: 'Blood group')), TextField(controller: hospital, decoration: const InputDecoration(labelText: 'Hospital name')), TextField(controller: phone, keyboardType: TextInputType.phone, decoration: const InputDecoration(labelText: 'Contact phone')), const SizedBox(height: 20), FilledButton.icon(onPressed: busy ? null : submit, icon: const Icon(Icons.warning), label: Text(busy ? 'Sending…' : 'Send critical request'))])); }
