import 'package:flutter/material.dart';
import '../../core/api/api_client.dart';
import '../../core/storage/token_storage.dart';
import 'auth_repository.dart';
import '../donor/donor_dashboard.dart';

class AuthScreen extends StatefulWidget { const AuthScreen({super.key}); @override State<AuthScreen> createState() => _AuthScreenState(); }
class _AuthScreenState extends State<AuthScreen> { final phone = TextEditingController(), password = TextEditingController(), name = TextEditingController(); bool register = false, busy = false; String role = 'DONOR';
  Future<void> submit() async { setState(() => busy = true); try { final repo = AuthRepository(ApiClient(), TokenStorage()); final result = register ? await repo.register({'phone': phone.text, 'password': password.text, 'full_name': name.text, 'role': role}) : await repo.login(phone.text, password.text); if (!mounted) return; Navigator.of(context).pushReplacement(MaterialPageRoute(builder: (_) => DonorDashboard(user: Map<String, dynamic>.from(result['user'] ?? {'role': role})))); } catch (e) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Unable to continue: $e'))); } finally { if (mounted) setState(() => busy = false); } }
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Blood Hub')), body: ListView(padding: const EdgeInsets.all(24), children: [Text(register ? 'Create account' : 'Welcome back', style: Theme.of(context).textTheme.headlineMedium), const SizedBox(height: 24), if (register) TextField(controller: name, decoration: const InputDecoration(labelText: 'Full name')), TextField(controller: phone, keyboardType: TextInputType.phone, decoration: const InputDecoration(labelText: 'Phone')), TextField(controller: password, obscureText: true, decoration: const InputDecoration(labelText: 'Password')), if (register) DropdownButtonFormField(value: role, items: const [DropdownMenuItem(value: 'DONOR', child: Text('Donor')), DropdownMenuItem(value: 'REQUESTER', child: Text('Requester'))], onChanged: (v) => setState(() => role = v!), decoration: const InputDecoration(labelText: 'Account type')), const SizedBox(height: 24), FilledButton(onPressed: busy ? null : submit, child: Text(busy ? 'Please wait…' : register ? 'Register' : 'Log in')), TextButton(onPressed: () => setState(() => register = !register), child: Text(register ? 'Already have an account? Log in' : 'Create an account'))])); }
