import 'package:flutter/material.dart';
import '../../core/api/api_client.dart';
import '../../core/location/location_service.dart';
import '../requester/emergency_request_screen.dart';
class DonorDashboard extends StatefulWidget { const DonorDashboard({super.key, required this.user}); final Map<String, dynamic> user; @override State<DonorDashboard> createState() => _DonorDashboardState(); }
class _DonorDashboardState extends State<DonorDashboard> { bool available = false, busy = false; final api = ApiClient();
 Future<void> toggle(bool value) async { setState(() { available = value; busy = true; }); try { await api.put('/donors/availability', data: {'availability_status': value ? 'AVAILABLE' : 'UNAVAILABLE'}); } catch (e) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Could not update availability: $e'))); } finally { if (mounted) setState(() => busy = false); } }
 Future<void> updateLocation() async { final p = await LocationService().currentPosition(); if (p != null) await api.put('/donors/location', data: {'latitude': p.latitude, 'longitude': p.longitude}); if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(p == null ? 'Location permission unavailable' : 'Location updated'))); }
 @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Donor dashboard')), body: ListView(padding: const EdgeInsets.all(20), children: [Text('Hello, ${widget.user['full_name'] ?? 'donor'}', style: Theme.of(context).textTheme.headlineSmall), Card(child: SwitchListTile(title: const Text('Available for emergency requests'), subtitle: Text(busy ? 'Updating…' : available ? 'You may receive offers' : 'Not receiving offers'), value: available, onChanged: busy ? null : toggle)), OutlinedButton.icon(onPressed: updateLocation, icon: const Icon(Icons.my_location), label: const Text('Update my location')), const SizedBox(height: 16), const Text('Offers will appear here when matched.'), if (widget.user['role'] == 'REQUESTER') FilledButton.icon(onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => const EmergencyRequestScreen())), icon: const Icon(Icons.emergency), label: const Text('Create emergency request'))])); }
